server:
  port: 8085

spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      management:
        context-path: /gateway/actuator
    health-check-url-path: /gateway/health
    status-page-url: /gateway/actuator/info
    home-page-url: /gateway
    lease-expiration-duration-in-seconds: 10

zuul:
  routes:
    consumer:
      path: /consumer/**
      service-id: consumer
    provider:
      path: /provider/**
      service-id: provider

ribbon:
  eager-load:
    enabled: true
